language: java
install: true
script: mvn install -Ptravis -Dmaven.javadoc.skip=true -B -V
notifications:
  slack: salvation-army-hq:EkwIpCtfHUURkQBvP2TKQiBj#travislog
    on_success: always
    on_failure: always